pipeline {
    agent any
    stages {
        stage ("Build Img") {
            steps {
                sh 'docker build -t $name_img $df_path'
            }
        }
        stage ("Deploy Img") {
            steps {
                sh 'docker run -itd --name $container_name -p $host_port:$container_port $name_img'
            }
        }
    }
}
